#ifndef EFILERESSOURCES_H
#define EFILERESSOURCES_H

#include "../resource.h"

enum EFILERESSOURCE
{
	ETS_CONVERTER_BASE = TS_CONVERTER_BASE,
	ETS_ASN1_BASE = TS_ASN1_BASE,
	ETS_ASN1_CLIENT = TS_ASN1_CLIENT,
	ETS_ASN1_NODE_CLIENT = TS_ASN1_NODE_CLIENT,
	ETS_ASN1_BROWSER_CLIENT = TS_ASN1_BROWSER_CLIENT,
	ETS_ASN1_SERVER = TS_ASN1_SERVER,
	ETS_ROSE_BASE = TS_ROSE_BASE,
	ETS_SNACCROSE = TS_SNACCROSE,
	ETS_SNACCROSE_CONVERTER = TS_SNACCROSE_CONVERTER,
	ETS_OPTIONALPARAM_CONVERTER = TS_OPTIONALPARAM_CONVERTER,
	ETS_DEPRECATED_CALLBACK = TS_DEPRECATED_CALLBACK,
	EDELPHI_ASN1_TYPES = DELPHI_ASN1_TYPES,
};

void SaveResourceToFile(enum EFILERESSOURCE esourceID, const char* szFileName);

#endif // EFILERESSOURCES_H