/*
 * This file was generated by estos esnacc (V6.0.12, 12.09.2024)
 * based on Coral WinSnacc written by Deepak Gupta
 * NOTE: This is a machine generated file - editing not recommended
*/

// prettier-ignore
/* eslint-disable */

export class Asn1InterfaceVersion {
	public static lastChange = "2024-05-06T00:00:00Z";
	public static majorVersion = 0;
	public static minorVersion = 1714953600;
	public static version = "0.1714953600.0";
}
