/**
 * This file exports all specified ROSE methods as arrays
 *
 * This file was generated by estos esnacc (V6.0.30, 10.07.2025)
 * based on Coral WinSnacc written by Deepak Gupta
 * NOTE: This is a machine generated file - editing not recommended
 */

// dprint-ignore-file
 

export interface IROSEMethod {
	name: string;
	id: number;
}

export interface IROSEMethodOverview {
	name: string;
	methods: IROSEMethod[];
}

export const methodsENetUCEventManager: IROSEMethod[] = [
	{ name: "asnCreateFancyEvents", id: 4000 },
	{ name: "asnFancyEvent", id: 4050 }
];

export const methodsENetUCSettingsManager: IROSEMethod[] = [
	{ name: "asnGetSettings", id: 4100 },
	{ name: "asnSetSettings", id: 4101 },
	{ name: "asnGetSettingsOld", id: 4102 },
	{ name: "asnSettingsChanged", id: 4150 }
];

export const roseInterfaceMethods: IROSEMethodOverview[] = [
	{ name: "ENetUCEventManager", methods: methodsENetUCEventManager },
	{ name: "ENetUCSettingsManager", methods: methodsENetUCSettingsManager }
];
