/*
 * This file was generated by estos esnacc (V6.0.31, 29.07.2025)
 * based on Coral WinSnacc written by Deepak Gupta
 * NOTE: This is a machine generated file - editing not recommended
*/

// dprint-ignore-file
/* eslint-disable */

export class Asn1InterfaceVersion {
	public static lastChange = "2024-05-06T00:00:00Z";
	public static majorVersion = 0;
	public static minorVersion = 0;
	public static patchVersion = 20240506;
	public static version = "0.0.20240506";
}
