// [PrintTSCode]
// [PrintTSComments]
/*
 * ENetUC_Common.ts
 * "UC-Server-Access-Protocol-Common" ASN.1 stubs.
 * This file was generated by estos esnacc (V5.0.18, 19.09.2023)
 * based on Coral WinSnacc written by Deepak Gupta
 * NOTE: This is a machine generated file - editing not recommended
 */

// prettier-ignore
/* eslint-disable */
// [PrintTSImports]
import * as asn1ts from "@estos/asn1ts";
// [PrintTSRootTypes]
export const moduleName = "ENetUC_Common";

// [PrintTSTypeDefCode]
// [PrintTSimpleDefCode]
export type AsnSystemTime = number;

// [PrintTSTypeDefCode]
// [PrintTSChoiceDefCode]
export class AsnOptionalParamChoice {
	public constructor(that?: AsnOptionalParamChoice) {
		Object.assign(this, that);
	}

	private static initEmpty(): AsnOptionalParamChoice {
		return new AsnOptionalParamChoice();
	}

	public static type = "AsnOptionalParamChoice";

	public static getASN1Schema(params?: asn1ts.ConstructedParams): asn1ts.Choice {
		return new asn1ts.Choice({
			name: "AsnOptionalParamChoice",
			...params,
			value: [
				new asn1ts.Utf8String({ name: "stringdata" }),
				new asn1ts.OctetString({ name: "binarydata" }),
				new asn1ts.Integer({ name: "integerdata" })
			]
		});
	}

	public stringdata?: string;
	public binarydata?: Uint8Array;
	public integerdata?: number;
}

// [PrintTSTypeDefCode]
// [PrintTSSeqDefCode]
export class AsnStringPair {
	public constructor(that: AsnStringPair) {
		Object.assign(this, that);
	}

	private static initEmpty(): AsnStringPair {
		return new AsnStringPair({
			key: "",
			value: ""
		});
	}

	public static type = "AsnStringPair";

	public static getASN1Schema(params?: asn1ts.ConstructedParams): asn1ts.Sequence {
		return new asn1ts.Sequence({
			name: "AsnStringPair",
			...params,
			value: [
				new asn1ts.Utf8String({ name: "key" }),
				new asn1ts.Utf8String({ name: "value" })
			]
		});
	}

	public key!: string;
	public value!: string;
}

// [PrintTSTypeDefCode]
// [PrintTSSeqDefCode]
export class AsnIntegerPair {
	public constructor(that: AsnIntegerPair) {
		Object.assign(this, that);
	}

	private static initEmpty(): AsnIntegerPair {
		return new AsnIntegerPair({
			key: 0,
			value: 0
		});
	}

	public static type = "AsnIntegerPair";

	public static getASN1Schema(params?: asn1ts.ConstructedParams): asn1ts.Sequence {
		return new asn1ts.Sequence({
			name: "AsnIntegerPair",
			...params,
			value: [
				new asn1ts.Integer({ name: "key" }),
				new asn1ts.Integer({ name: "value" })
			]
		});
	}

	public key!: number;
	public value!: number;
}

// [PrintTSTypeDefCode]
// [PrintTSSeqDefCode]
export class AsnStringIntegerPair {
	public constructor(that: AsnStringIntegerPair) {
		Object.assign(this, that);
	}

	private static initEmpty(): AsnStringIntegerPair {
		return new AsnStringIntegerPair({
			u8sStr: "",
			iInt: 0
		});
	}

	public static type = "AsnStringIntegerPair";

	public static getASN1Schema(params?: asn1ts.ConstructedParams): asn1ts.Sequence {
		return new asn1ts.Sequence({
			name: "AsnStringIntegerPair",
			...params,
			value: [
				new asn1ts.Utf8String({ name: "u8sStr" }),
				new asn1ts.Integer({ name: "iInt" })
			]
		});
	}

	public u8sStr!: string;
	public iInt!: number;
}

// [PrintTSTypeDefCode]
// [PrintTSSeqDefCode]
export class AsnRequestError {
	public constructor(that: AsnRequestError) {
		Object.assign(this, that);
	}

	private static initEmpty(): AsnRequestError {
		return new AsnRequestError({
			iErrorDetail: 0,
			u8sErrorString: ""
		});
	}

	public static type = "AsnRequestError";

	public static getASN1Schema(params?: asn1ts.ConstructedParams): asn1ts.Sequence {
		return new asn1ts.Sequence({
			name: "AsnRequestError",
			...params,
			value: [
				new asn1ts.Integer({ name: "iErrorDetail" }),
				new asn1ts.Utf8String({ name: "u8sErrorString" })
			]
		});
	}

	public iErrorDetail!: number;
	public u8sErrorString!: string;
}

// [PrintTSTypeDefCode]
// [PrintTSSeqDefCode]
export class AsnNetDatabaseContactID {
	public constructor(that: AsnNetDatabaseContactID) {
		Object.assign(this, that);
	}

	private static initEmpty(): AsnNetDatabaseContactID {
		return new AsnNetDatabaseContactID({
			u8sEntryID: "",
			u8sEntryIDDB: "",
			u8sEntryIDStore: ""
		});
	}

	public static type = "AsnNetDatabaseContactID";

	public static getASN1Schema(params?: asn1ts.ConstructedParams): asn1ts.Sequence {
		return new asn1ts.Sequence({
			name: "AsnNetDatabaseContactID",
			...params,
			value: [
				new asn1ts.Utf8String({ name: "u8sEntryID" }),
				new asn1ts.Utf8String({ name: "u8sEntryIDDB" }),
				new asn1ts.Utf8String({ name: "u8sEntryIDStore" })
			]
		});
	}

	public u8sEntryID!: string;
	public u8sEntryIDDB!: string;
	public u8sEntryIDStore!: string;
}

// [PrintTSTypeDefCode]
// [PrintTSSeqDefCode]
export class AsnOptionalParam {
	public constructor(that: AsnOptionalParam) {
		Object.assign(this, that);
	}

	private static initEmpty(): AsnOptionalParam {
		return new AsnOptionalParam({
			key: "",
			value: AsnOptionalParamChoice["initEmpty"].call(0)
		});
	}

	public static type = "AsnOptionalParam";

	public static getASN1Schema(params?: asn1ts.ConstructedParams): asn1ts.Sequence {
		return new asn1ts.Sequence({
			name: "AsnOptionalParam",
			...params,
			value: [
				new asn1ts.Utf8String({ name: "key" }),
				AsnOptionalParamChoice.getASN1Schema({ name: "value" })
			]
		});
	}

	public key!: string;
	public value!: AsnOptionalParamChoice;
}

// [PrintTSTypeDefCode]
// [PrintTSSetOfDefCode]
// [PrintTSListClass]
export class AsnStringPairList extends Array<AsnStringPair> {
	public static getASN1Schema(params?: asn1ts.SequenceOfParams): asn1ts.SequenceOf {
		return new asn1ts.SequenceOf({
			...params,
			value: AsnStringPair.getASN1Schema()
		});
	}
}

// [PrintTSTypeDefCode]
// [PrintTSSeqDefCode]
export class AsnJSONWebTokenHeader {
	public constructor(that: AsnJSONWebTokenHeader) {
		Object.assign(this, that);
	}

	private static initEmpty(): AsnJSONWebTokenHeader {
		return new AsnJSONWebTokenHeader({
			u8sTYP: "",
			u8sALG: ""
		});
	}

	public static type = "AsnJSONWebTokenHeader";

	public static getASN1Schema(params?: asn1ts.ConstructedParams): asn1ts.Sequence {
		return new asn1ts.Sequence({
			name: "AsnJSONWebTokenHeader",
			...params,
			value: [
				new asn1ts.Utf8String({ name: "u8sTYP" }),
				new asn1ts.Utf8String({ name: "u8sALG" }),
				new asn1ts.Utf8String({ name: "u8sCTY", idBlock: { optionalID: 0 } }),
				AsnStringPairList.getASN1Schema({ name: "optionals", idBlock: { optionalID: 1 } })
			]
		});
	}

	public u8sTYP!: string;
	public u8sALG!: string;
	public u8sCTY?: string;
	public optionals?: AsnStringPairList;
}

// [PrintTSTypeDefCode]
// [PrintTSSeqDefCode]
export class AsnJSONWebTokenPayLoad {
	public constructor(that: AsnJSONWebTokenPayLoad) {
		Object.assign(this, that);
	}

	private static initEmpty(): AsnJSONWebTokenPayLoad {
		return new AsnJSONWebTokenPayLoad({
			u8sJTI: ""
		});
	}

	public static type = "AsnJSONWebTokenPayLoad";

	public static getASN1Schema(params?: asn1ts.ConstructedParams): asn1ts.Sequence {
		return new asn1ts.Sequence({
			name: "AsnJSONWebTokenPayLoad",
			...params,
			value: [
				new asn1ts.Utf8String({ name: "u8sISS", idBlock: { optionalID: 0 } }),
				new asn1ts.Utf8String({ name: "u8sSUB", idBlock: { optionalID: 1 } }),
				new asn1ts.Utf8String({ name: "u8sAUD", idBlock: { optionalID: 2 } }),
				new asn1ts.Real({ name: "utcEXP", idBlock: { optionalID: 3 } }),
				new asn1ts.Real({ name: "utcNBF", idBlock: { optionalID: 4 } }),
				new asn1ts.Real({ name: "utcIAT", idBlock: { optionalID: 5 } }),
				new asn1ts.Utf8String({ name: "u8sJTI" }),
				new asn1ts.Integer({ name: "iUserType", idBlock: { optionalID: 6 } }),
				AsnStringPairList.getASN1Schema({ name: "optionals", idBlock: { optionalID: 7 } })
			]
		});
	}

	public u8sISS?: string;
	public u8sSUB?: string;
	public u8sAUD?: string;
	public utcEXP?: Date;
	public utcNBF?: Date;
	public utcIAT?: Date;
	public u8sJTI!: string;
	public iUserType?: number;
	public optionals?: AsnStringPairList;
}

// [PrintTSTypeDefCode]
// [PrintTSSetOfDefCode]
// [PrintTSListClass]
export class AsnOptionalParameters extends Array<AsnOptionalParam> {
	public static getASN1Schema(params?: asn1ts.SequenceOfParams): asn1ts.SequenceOf {
		return new asn1ts.SequenceOf({
			...params,
			value: AsnOptionalParam.getASN1Schema()
		});
	}
}

// [PrintTSTypeDefCode]
// [PrintTSSeqDefCode]
export class AsnNetDatabaseContact {
	public constructor(that?: AsnNetDatabaseContact) {
		Object.assign(this, that);
	}

	private static initEmpty(): AsnNetDatabaseContact {
		return new AsnNetDatabaseContact();
	}

	public static type = "AsnNetDatabaseContact";

	public static getASN1Schema(params?: asn1ts.ConstructedParams): asn1ts.Sequence {
		return new asn1ts.Sequence({
			name: "AsnNetDatabaseContact",
			...params,
			value: [
				new asn1ts.Utf8String({ name: "u8sFound", idBlock: { optionalID: 0 } }),
				new asn1ts.Utf8String({ name: "u8sDatabaseName", idBlock: { optionalID: 1 } }),
				new asn1ts.Utf8String({ name: "u8sEntryIDDB", idBlock: { optionalID: 2 } }),
				new asn1ts.Utf8String({ name: "u8sEntryIDStore", idBlock: { optionalID: 3 } }),
				new asn1ts.Utf8String({ name: "u8sEntryID", idBlock: { optionalID: 4 } }),
				new asn1ts.Utf8String({ name: "u8sCtiServerUserName", idBlock: { optionalID: 5 } }),
				new asn1ts.Utf8String({ name: "u8sDisplayName", idBlock: { optionalID: 6 } }),
				new asn1ts.Utf8String({ name: "u8sFirstName", idBlock: { optionalID: 7 } }),
				new asn1ts.Utf8String({ name: "u8sLastName", idBlock: { optionalID: 8 } }),
				new asn1ts.Utf8String({ name: "u8sJobTitle", idBlock: { optionalID: 9 } }),
				new asn1ts.Utf8String({ name: "u8sCompany", idBlock: { optionalID: 10 } }),
				new asn1ts.Utf8String({ name: "u8sDepartment", idBlock: { optionalID: 11 } }),
				new asn1ts.Utf8String({ name: "u8sOfficeRoomNumber", idBlock: { optionalID: 12 } }),
				new asn1ts.Utf8String({ name: "u8sCustomerID", idBlock: { optionalID: 13 } }),
				new asn1ts.Utf8String({ name: "u8sBusinessAddressStreet", idBlock: { optionalID: 14 } }),
				new asn1ts.Utf8String({ name: "u8sBusinessAddressPostalCode", idBlock: { optionalID: 15 } }),
				new asn1ts.Utf8String({ name: "u8sBusinessAddressCity", idBlock: { optionalID: 16 } }),
				new asn1ts.Utf8String({ name: "u8sBusinessAddressState", idBlock: { optionalID: 17 } }),
				new asn1ts.Utf8String({ name: "u8sBusinessAddressCountry", idBlock: { optionalID: 18 } }),
				new asn1ts.Utf8String({ name: "u8sPrivateAddressStreet", idBlock: { optionalID: 19 } }),
				new asn1ts.Utf8String({ name: "u8sPrivateAddressPostalCode", idBlock: { optionalID: 20 } }),
				new asn1ts.Utf8String({ name: "u8sPrivateAddressCity", idBlock: { optionalID: 21 } }),
				new asn1ts.Utf8String({ name: "u8sPrivateAddressState", idBlock: { optionalID: 22 } }),
				new asn1ts.Utf8String({ name: "u8sPrivateAddressCountry", idBlock: { optionalID: 23 } }),
				new asn1ts.Utf8String({ name: "u8sOtherAddressStreet", idBlock: { optionalID: 24 } }),
				new asn1ts.Utf8String({ name: "u8sOtherAddressPostalCode", idBlock: { optionalID: 25 } }),
				new asn1ts.Utf8String({ name: "u8sOtherAddressCity", idBlock: { optionalID: 26 } }),
				new asn1ts.Utf8String({ name: "u8sOtherAddressState", idBlock: { optionalID: 27 } }),
				new asn1ts.Utf8String({ name: "u8sOtherAddressCountry", idBlock: { optionalID: 28 } }),
				new asn1ts.Utf8String({ name: "u8sEMail", idBlock: { optionalID: 29 } }),
				new asn1ts.Utf8String({ name: "u8sEMail2", idBlock: { optionalID: 30 } }),
				new asn1ts.Utf8String({ name: "u8sEMail3", idBlock: { optionalID: 31 } }),
				new asn1ts.Utf8String({ name: "u8sSIPAddress", idBlock: { optionalID: 32 } }),
				new asn1ts.Utf8String({ name: "u8sWebPageURL", idBlock: { optionalID: 33 } }),
				new asn1ts.Utf8String({ name: "u8sPhoneBusiness", idBlock: { optionalID: 34 } }),
				new asn1ts.Utf8String({ name: "u8sPhoneBusiness2", idBlock: { optionalID: 35 } }),
				new asn1ts.Utf8String({ name: "u8sCompanyMainTelephoneNumber", idBlock: { optionalID: 36 } }),
				new asn1ts.Utf8String({ name: "u8sAssistantTelephoneNumber", idBlock: { optionalID: 37 } }),
				new asn1ts.Utf8String({ name: "u8sPhoneHome", idBlock: { optionalID: 38 } }),
				new asn1ts.Utf8String({ name: "u8sPhoneHome2", idBlock: { optionalID: 39 } }),
				new asn1ts.Utf8String({ name: "u8sPrimaryTelephoneNumber", idBlock: { optionalID: 40 } }),
				new asn1ts.Utf8String({ name: "u8sPhoneMobile", idBlock: { optionalID: 41 } }),
				new asn1ts.Utf8String({ name: "u8sCarTelephoneNumber", idBlock: { optionalID: 42 } }),
				new asn1ts.Utf8String({ name: "u8sRadioTelephoneNumber", idBlock: { optionalID: 43 } }),
				new asn1ts.Utf8String({ name: "u8sPagerTelephoneNumber", idBlock: { optionalID: 44 } }),
				new asn1ts.Utf8String({ name: "u8sOtherTelephoneNumber", idBlock: { optionalID: 45 } }),
				new asn1ts.Utf8String({ name: "u8sCallbackTelephoneNumber", idBlock: { optionalID: 46 } }),
				new asn1ts.Utf8String({ name: "u8sISDNTelephoneNumber", idBlock: { optionalID: 47 } }),
				new asn1ts.Utf8String({ name: "u8sTTYTTDTelephoneNumber", idBlock: { optionalID: 48 } }),
				new asn1ts.Utf8String({ name: "u8sFaxBusiness", idBlock: { optionalID: 49 } }),
				new asn1ts.Utf8String({ name: "u8sFaxHome", idBlock: { optionalID: 50 } }),
				new asn1ts.Utf8String({ name: "u8sBody", idBlock: { optionalID: 51 } }),
				new asn1ts.Utf8String({ name: "u8sDirectWebLink", idBlock: { optionalID: 52 } }),
				AsnStringPairList.getASN1Schema({ name: "customFields", idBlock: { optionalID: 53 } }),
				new asn1ts.Boolean({ name: "bValid", idBlock: { optionalID: 54 } }),
				new asn1ts.Integer({ name: "iPrivateContact", idBlock: { optionalID: 55 } }),
				new asn1ts.Integer({ name: "iCtiServerUser", idBlock: { optionalID: 56 } }),
				AsnOptionalParameters.getASN1Schema({ name: "optionalParams", idBlock: { optionalID: 57 } })
			]
		});
	}

	public u8sFound?: string;
	public u8sDatabaseName?: string;
	public u8sEntryIDDB?: string;
	public u8sEntryIDStore?: string;
	public u8sEntryID?: string;
	public u8sCtiServerUserName?: string;
	public u8sDisplayName?: string;
	public u8sFirstName?: string;
	public u8sLastName?: string;
	public u8sJobTitle?: string;
	public u8sCompany?: string;
	public u8sDepartment?: string;
	public u8sOfficeRoomNumber?: string;
	public u8sCustomerID?: string;
	public u8sBusinessAddressStreet?: string;
	public u8sBusinessAddressPostalCode?: string;
	public u8sBusinessAddressCity?: string;
	public u8sBusinessAddressState?: string;
	public u8sBusinessAddressCountry?: string;
	public u8sPrivateAddressStreet?: string;
	public u8sPrivateAddressPostalCode?: string;
	public u8sPrivateAddressCity?: string;
	public u8sPrivateAddressState?: string;
	public u8sPrivateAddressCountry?: string;
	public u8sOtherAddressStreet?: string;
	public u8sOtherAddressPostalCode?: string;
	public u8sOtherAddressCity?: string;
	public u8sOtherAddressState?: string;
	public u8sOtherAddressCountry?: string;
	public u8sEMail?: string;
	public u8sEMail2?: string;
	public u8sEMail3?: string;
	public u8sSIPAddress?: string;
	public u8sWebPageURL?: string;
	public u8sPhoneBusiness?: string;
	public u8sPhoneBusiness2?: string;
	public u8sCompanyMainTelephoneNumber?: string;
	public u8sAssistantTelephoneNumber?: string;
	public u8sPhoneHome?: string;
	public u8sPhoneHome2?: string;
	public u8sPrimaryTelephoneNumber?: string;
	public u8sPhoneMobile?: string;
	public u8sCarTelephoneNumber?: string;
	public u8sRadioTelephoneNumber?: string;
	public u8sPagerTelephoneNumber?: string;
	public u8sOtherTelephoneNumber?: string;
	public u8sCallbackTelephoneNumber?: string;
	public u8sISDNTelephoneNumber?: string;
	public u8sTTYTTDTelephoneNumber?: string;
	public u8sFaxBusiness?: string;
	public u8sFaxHome?: string;
	public u8sBody?: string;
	public u8sDirectWebLink?: string;
	public customFields?: AsnStringPairList;
	public bValid?: boolean;
	public iPrivateContact?: number;
	public iCtiServerUser?: number;
	public optionalParams?: AsnOptionalParameters;
}

// [PrintTSTypeDefCode]
// [PrintTSSetOfDefCode]
// [PrintTSListClass]
export class AsnIntegerPairList extends Array<AsnIntegerPair> {
	public static getASN1Schema(params?: asn1ts.SequenceOfParams): asn1ts.SequenceOf {
		return new asn1ts.SequenceOf({
			...params,
			value: AsnIntegerPair.getASN1Schema()
		});
	}
}

// [PrintTSTypeDefCode]
// [PrintTSSetOfDefCode]
// [PrintTSListClass]
export class AsnStringIntegerPairList extends Array<AsnStringIntegerPair> {
	public static getASN1Schema(params?: asn1ts.SequenceOfParams): asn1ts.SequenceOf {
		return new asn1ts.SequenceOf({
			...params,
			value: AsnStringIntegerPair.getASN1Schema()
		});
	}
}

// [PrintTSTypeDefCode]
// [PrintTSSetOfDefCode]
// [PrintTSListClass]
export class AsnRequestErrorList extends Array<AsnRequestError> {
	public static getASN1Schema(params?: asn1ts.SequenceOfParams): asn1ts.SequenceOf {
		return new asn1ts.SequenceOf({
			...params,
			value: AsnRequestError.getASN1Schema()
		});
	}
}

// [PrintTSTypeDefCode]
// [PrintTSSetOfDefCode]
// [PrintTSListClass]
export class SEQInteger extends Array<number> {
	public static getASN1Schema(params?: asn1ts.SequenceOfParams): asn1ts.SequenceOf {
		return new asn1ts.SequenceOf({
			...params,
			value: new asn1ts.Integer()
		});
	}
}

// [PrintTSTypeDefCode]
// [PrintTSSetOfDefCode]
// [PrintTSListClass]
export class UTF8StringList extends Array<string> {
	public static getASN1Schema(params?: asn1ts.SequenceOfParams): asn1ts.SequenceOf {
		return new asn1ts.SequenceOf({
			...params,
			value: new asn1ts.Utf8String()
		});
	}
}

// [PrintTSTypeDefCode]
// [PrintTSSetOfDefCode]
// [PrintTSListClass]
export class AsnNetDatabaseContactList extends Array<AsnNetDatabaseContact> {
	public static getASN1Schema(params?: asn1ts.SequenceOfParams): asn1ts.SequenceOf {
		return new asn1ts.SequenceOf({
			...params,
			value: AsnNetDatabaseContact.getASN1Schema()
		});
	}
}

// [PrintTSTypeDefCode]
// [PrintTSSetOfDefCode]
// [PrintTSListClass]
export class AsnNetDatabaseContactIDList extends Array<AsnNetDatabaseContactID> {
	public static getASN1Schema(params?: asn1ts.SequenceOfParams): asn1ts.SequenceOf {
		return new asn1ts.SequenceOf({
			...params,
			value: AsnNetDatabaseContactID.getASN1Schema()
		});
	}
}

// [PrintTSTypeDefCode]
// [PrintTSSeqDefCode]
export class AsnUserPropertyBag {
	public constructor(that: AsnUserPropertyBag) {
		Object.assign(this, that);
	}

	private static initEmpty(): AsnUserPropertyBag {
		return new AsnUserPropertyBag({
			asnProperties: new AsnStringPairList()
		});
	}

	public static type = "AsnUserPropertyBag";

	public static getASN1Schema(params?: asn1ts.ConstructedParams): asn1ts.Sequence {
		return new asn1ts.Sequence({
			name: "AsnUserPropertyBag",
			...params,
			value: [
				AsnStringPairList.getASN1Schema({ name: "asnProperties" })
			]
		});
	}

	public asnProperties!: AsnStringPairList;
}

// [PrintTSTypeDefCode]
// [PrintTSSeqDefCode]
export class AsnJSONWebToken {
	public constructor(that: AsnJSONWebToken) {
		Object.assign(this, that);
	}

	private static initEmpty(): AsnJSONWebToken {
		return new AsnJSONWebToken({
			header: AsnJSONWebTokenHeader["initEmpty"].call(0),
			payload: AsnJSONWebTokenPayLoad["initEmpty"].call(0),
			signature: ""
		});
	}

	public static type = "AsnJSONWebToken";

	public static getASN1Schema(params?: asn1ts.ConstructedParams): asn1ts.Sequence {
		return new asn1ts.Sequence({
			name: "AsnJSONWebToken",
			...params,
			value: [
				AsnJSONWebTokenHeader.getASN1Schema({ name: "header" }),
				AsnJSONWebTokenPayLoad.getASN1Schema({ name: "payload" }),
				new asn1ts.Utf8String({ name: "signature" })
			]
		});
	}

	public header!: AsnJSONWebTokenHeader;
	public payload!: AsnJSONWebTokenPayLoad;
	public signature!: string;
}
