/**
 * This file exports all specified ROSE methods as arrays
 *
 * This file was generated by estos esnacc 4.x
 * based on Coral WinSnacc written by Deepak Gupta
 * NOTE: This is a machine generated file - editing not recommended
 */

export interface IROSEMethod {
	name: string;
	id: number;
}

export interface IROSEMethodOverview {
	name: string;
	methods: IROSEMethod[];
}

