// [PrintTSSerializableCode]
// [PrintTSSerializableComments]
/*
 * SNACCROSE_Serializable.ts
 * "SNACC-ROSE" ASN.1 serializable type definitions for Redux-safe plain objects.
 * This file was generated by estos esnacc (V7.0.19, 18.09.2026)
 * based on Coral WinSnacc written by Deepak Gupta
 * NOTE: This is a machine generated file - editing not recommended
 */

// dprint-ignore-file
/* eslint-disable */
// [PrintTSSerializableImports]

// [PrintTSSerializableTypeDefCode]
export type IGeneralProblem = number;

// [PrintTSSerializableTypeDefCode]
export type IInvokeProblem = number;

// [PrintTSSerializableTypeDefCode]
export type IReturnResultProblem = number;

// [PrintTSSerializableTypeDefCode]
export type IReturnErrorProblem = number;

// [PrintTSSerializableTypeDefCode]
// [PrintTSSerializableChoiceDefCode]
export interface IROSERejectChoice {
	/** Optional ASN.1 type discriminator when converters encode with bAddTypes. */
	_type?: string;
	invokedID?: number;

	invokednull?: null;
}

// [PrintTSSerializableTypeDefCode]
// [PrintTSSerializableSeqDefCode]
export interface IROSEResultSeq {
	/** Optional ASN.1 type discriminator when converters encode with bAddTypes. */
	_type?: string;
	resultValue: number;

	result: unknown;
}

// [PrintTSSerializableTypeDefCode]
// [PrintTSSerializableSeqDefCode]
export interface IROSEAuth {
	/** Optional ASN.1 type discriminator when converters encode with bAddTypes. */
	_type?: string;
	method: string;

	authdata: string;
}

// [PrintTSSerializableTypeDefCode]
// [PrintTSSerializableSeqDefCode]
export interface IROSEError {
	/** Optional ASN.1 type discriminator when converters encode with bAddTypes. */
	_type?: string;
	sessionID?: string;

	invokedID: number;

	error_value: number;

	error?: unknown;
}

// [PrintTSSerializableTypeDefCode]
// [PrintTSSerializableListType]
export type IROSEAuthList = IROSEAuth[];

// [PrintTSSerializableTypeDefCode]
// [PrintTSSerializableSeqDefCode]
export interface IROSEAuthRequest {
	/** Optional ASN.1 type discriminator when converters encode with bAddTypes. */
	_type?: string;
	auth: IROSEAuth;

	context?: string;
}

// [PrintTSSerializableTypeDefCode]
// [PrintTSSerializableSeqDefCode]
export interface IROSEAuthResult {
	/** Optional ASN.1 type discriminator when converters encode with bAddTypes. */
	_type?: string;
	authList: IROSEAuthList;

	context?: string;
}

// [PrintTSSerializableTypeDefCode]
// [PrintTSSerializableSeqDefCode]
export interface IROSEInvoke {
	/** Optional ASN.1 type discriminator when converters encode with bAddTypes. */
	_type?: string;
	sessionID?: string;

	invokeID: number;

	linked_ID?: number;

	operationName?: string;

	authentication?: IROSEAuthRequest;

	timeout?: number;

	operationID: number;

	argument?: unknown;
}

// [PrintTSSerializableTypeDefCode]
// [PrintTSSerializableSeqDefCode]
export interface IROSEResult {
	/** Optional ASN.1 type discriminator when converters encode with bAddTypes. */
	_type?: string;
	sessionID?: string;

	invokeID: number;

	result?: IROSEResultSeq;
}

// [PrintTSSerializableTypeDefCode]
// [PrintTSSerializableChoiceDefCode]
export interface IRejectProblem {
	/** Optional ASN.1 type discriminator when converters encode with bAddTypes. */
	_type?: string;
	generalProblem?: number;

	invokeProblem?: number;

	returnResultProblem?: number;

	returnErrorProblem?: number;
}

// [PrintTSSerializableTypeDefCode]
// [PrintTSSerializableSeqDefCode]
export interface IROSEReject {
	/** Optional ASN.1 type discriminator when converters encode with bAddTypes. */
	_type?: string;
	sessionID?: string;

	invokedID: IROSERejectChoice;

	reject?: IRejectProblem;

	details?: string;

	authentication?: IROSEAuthResult;
}

// [PrintTSSerializableTypeDefCode]
// [PrintTSSerializableChoiceDefCode]
export interface IROSEMessage {
	/** Optional ASN.1 type discriminator when converters encode with bAddTypes. */
	_type?: string;
	invoke?: IROSEInvoke;

	result?: IROSEResult;

	error?: IROSEError;

	reject?: IROSEReject;
}
